// SPDX-License-Identifier: MIT
using AgentBoard.Domain.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentBoard.Infrastructure.Persistence.Configurations;

/// <summary>EF Core mapping for <see cref="User"/>. Column names mirror the
/// FastAPI schema (snake_case) so a single MariaDB instance can serve both
/// stacks. The fastapi side is generated by SQLAlchemy which also uses
/// snake_case by default.</summary>
public sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> b)
    {
        b.ToTable("users");
        b.HasKey(u => u.Id);
        b.Property(u => u.Id).HasColumnName("id").ValueGeneratedOnAdd();
        b.Property(u => u.Username).HasColumnName("username").HasMaxLength(64).IsRequired();
        b.HasIndex(u => u.Username).IsUnique();
        b.Property(u => u.PasswordHash).HasColumnName("password_hash").HasMaxLength(255).IsRequired();
        b.Property(u => u.DisplayName).HasColumnName("display_name").HasMaxLength(128);
        b.Property(u => u.Email).HasColumnName("email").HasMaxLength(255);
        b.Property(u => u.AvatarUrl).HasColumnName("avatar_url").HasMaxLength(512);
        b.Property(u => u.IsAdmin).HasColumnName("is_admin").HasDefaultValue(false);

        b.Property(u => u.RowVersion).HasColumnName("row_version")
            .IsConcurrencyToken().ValueGeneratedOnAddOrUpdate();

        b.Property(u => u.CreatedAt).HasColumnName("created_at");
        b.Property(u => u.UpdatedAt).HasColumnName("updated_at");
        b.Property(u => u.CreatedBy).HasColumnName("created_by");
        b.Property(u => u.UpdatedBy).HasColumnName("updated_by");
    }
}
