// SPDX-License-Identifier: MIT
using AgentBoard.Domain.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentBoard.Infrastructure.Persistence.Configurations;

/// <summary>EF Core mapping for <see cref="User"/>. Column names mirror the
/// FastAPI schema (snake_case) so a single MariaDB instance can serve both
/// stacks. The fastapi side is generated by SQLAlchemy which also uses
/// snake_case by default.</summary>
public sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> b)
    {
        b.ToTable("users");
        b.HasKey(u => u.Id);
        b.Property(u => u.Id).HasColumnName("id").ValueGeneratedOnAdd();
        b.Property(u => u.Username).HasColumnName("username").HasMaxLength(64).IsRequired();
        b.HasIndex(u => u.Username).IsUnique();
        b.Property(u => u.PasswordHash).HasColumnName("password_hash").HasMaxLength(255).IsRequired();
        b.Property(u => u.DisplayName).HasColumnName("display_name").HasMaxLength(128);
        b.Property(u => u.Email).HasColumnName("email").HasMaxLength(255);
        b.Property(u => u.AvatarUrl).HasColumnName("avatar_url").HasMaxLength(512);
        b.Property(u => u.IsAdmin).HasColumnName("is_admin").HasDefaultValue(false);

        b.Property(u => u.CreatedAt).HasColumnName("created_at");

        // The FastAPI `users` table carries no audit/version columns
        // (created_by, updated_by, updated_at, row_version) and no domain
        // event storage. Those properties exist on the entity for write-path
        // parity but MUST NOT be mapped to the shared schema — mapping them
        // makes every users query throw "no such column: u.created_by".
        b.Ignore(u => u.UpdatedAt);
        b.Ignore(u => u.CreatedBy);
        b.Ignore(u => u.UpdatedBy);
        b.Ignore(u => u.RowVersion);
        b.Ignore(u => u.DomainEvents);
    }
}
